### ISSUE TITLE
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException'

### ISSUE THREAD

**Issue by Tokipudi** [teamreflex/discord-oauth#18]
Hey,

I managed to get this working (kinda) by adding `require "vendor/autoload.php";` at the beginning of the PHP code you wrote, but once I click on **Authorize** I get back to the index with this lengthy error that I don't understand. 

What it returns exactly : 

`Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in D:\jsd31\Documents\Freelance\Perso\Movie of the week\form\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 D:\jsd31\Documents\Freelance\Perso\Movie of the week\form\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\jsd31\Documents\Freelance\Perso\Movie of the week\form\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\jsd31\Documents\Freelance\Perso\Movie of the week\form\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\Cur in D:\jsd31\Documents\Freelance\Perso\Movie of the week\form\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187`

The main url of the project is `localhost/myproject/index.php` and the one which shows this message is `localhost/myproject/index.php?state=0imChXLChR4G67XzbZnGZLqJNewgsxFi&code=cpwGRRJejzR6nj7HFSCCChiglk8Utg` 

Do you have any idea as to what could be the problem here ?

Thank you for your time.

**Comment by Tokipudi** [comment]
I have done what is said in [this link](https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate) to deal with this issue, but I still have another one that says : 

`Notice: Undefined variable: getOldTokenFromMemory in D:\jsd31\Documents\Freelance\Perso\Movie of the week\form\oauth2-discord.php on line 30
Fatal error: Call to a member function getRefreshToken() on null in D:\jsd31\Documents\Freelance\Perso\Movie of the week\form\oauth2-discord.php on line 30` 

Even though the client_id, client_secret and redirectUri are all entered and correct.
